#!/usr/bin/env python3

import os
import sys

from lexer import Lexer
from parser import Parser
from utils import ErrorHandler, FNF, usage

DEBUG = False


def compile_file(filename):
    global DEBUG
    lex_out = Lexer(filename).analyze()
    if DEBUG:
        with open(filename.split('.', 1)[0] + ".txt", "w") as f:
            print(*lex_out, sep='\n', file=f)
    parse_out = Parser(lex_out).parse()
    if DEBUG:
        with open(filename.split('.', 1)[0] + ".py", "w") as f:
            import ast
            print(ast.dump(parse_out), file=f)
    return compile(parse_out, "<ast>", "exec")


def execute(filename):
    ast_module = compile_file(filename)
    exec(ast_module)


def main():
    # if len(sys.argv) < 2 or '-h' in sys.argv or '--help' in sys.argv:
    #     usage()
    
    # filename = sys.argv[-1]
    filename = "modi.chai"
    if '-d' in sys.argv or '--debug' in sys.argv:
        global DEBUG
        DEBUG = True
    
    # check existence
    if not os.path.isfile(filename):
        raise ErrorHandler(FNF, filename)
    # execute
    execute(filename)

if __name__ == '__main__':
    try:
        main()
    except ErrorHandler as e:
        print(e)
